//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace university_online_assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer_Profile
    {
        public System.Guid Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string icNum { get; set; }
        public byte[] birthDate { get; set; }
        public string gender { get; set; }
        public string contactNo { get; set; }
        public string address { get; set; }
        public string faculty { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
