//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace university_online_assessment.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Student_Assessment
    {
        public System.Guid Id { get; set; }
        public System.Guid studentId { get; set; }
        public System.Guid assessmentId { get; set; }
        public int score { get; set; }
        public System.DateTime dateFinished { get; set; }

        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Assessment Assessment { get; set; }

        public String getGrade()
        {
            String grade = "Not graded";

            int score = this.score;

            if (score >= 80)
                grade = "A";
            else if (score >= 60 && score <= 79)
                grade = "B";
            else if (score >= 50 && score <= 59)
                grade = "C";
            else if (score >= 40 && score <= 49)
                grade = "D";
            else if (score >= 0 && score <= 39)
                grade = "F";

            return grade;
        }
    }
}
