//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace university_online_assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Answer
    {
        public System.Guid questionId { get; set; }
        public System.Guid studentId { get; set; }
        public string studentAnswer { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Question Question { get; set; }
    }
}
